# own properties
moviepumpkins.integration.keycloak.auth-server-url-base=http://localhost:9090
# data source
spring.datasource.url=jdbc:postgresql://localhost:5432/pumpkins
spring.datasource.username=admin
spring.datasource.password=gYLWLbQUcY
# security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/moviepumpkins
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:9090/realms/moviepumpkins/protocol/openid-connect/token
spring.security.oauth2.client.registration.keycloak.client-id=moviepumpkins-backend-core
# logging
logging.level.net.moviepumpkins.core=debug
