app:
  scoring:
    min-score: 1
    max-score: 5
    page-size: 12
  reviewing:
    page-size: 5
spring:
  profiles:
    active: dev
  application:
    name: MoviePumpkins Backend Core
  jpa:
    database: postgresql
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        default_schema: app
        id:
          db_structure_naming_strategy: net.moviepumpkins.core.app.config.PostgresSequenceNamingStrategy
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    default-schema: app
    enabled: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials