app:
  auth-server-url-base: http://localhost:9090
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/pumpkins
    username: admin
    password: gYLWLbQUcY
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/moviepumpkins
      client:
        provider:
          keycloak:
            token-uri: http://localhost:9090/realms/moviepumpkins/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: pumpkins-backend-core
            client-secret: K2BZ3BRrmNjaDJ0kiz59Bgakv77JuaaD