openapi: 3.0.2
info:
  version: '1.0.0'
  title: net.moviepumpkins.core
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  '/spec':
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Specification'
  '/users/{username}/protected':
    get:
      operationId: getUserProtected
      security:
        - bearerAuth: [ ]
      parameters:
        #[CLIENT_ONLY] - $ref: '#/components/parameters/Authorization'
        - name: username
          schema:
            type: string
          required: true
          description: search by username
          in: path
      responses:
        '200':
          description: you successfully got back attributes of a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProtectedUserResponse'
        '404':
          description: user with username couldn't be found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status4xxResponse'
  '/users/{username}/profile':
    put:
      operationId: updateUserProfile
      security:
        - bearerAuth: [ ]
      parameters:
        #[CLIENT_ONLY] - $ref: '#/components/parameters/Authorization'
        - name: username
          schema:
            type: string
          required: true
          description: search by username
          in: path
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserProfileRequest'
      responses:
        '401':
          description: you must be logged in to modify the profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status4xxResponse'
        '403':
          description: you are not authorized to modify this profile!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status4xxResponse'
        '400':
          description: request body is incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status400Response'
        '204':
          description: profile modified successfully

    get:
      operationId: getUserProfile
      parameters:
        - name: username
          schema:
            type: string
          required: true
          description: search by username
          in: path
      responses:
        '200':
          description: you successfully got back attributes of a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserProfileResponse'
        '404':
          description: user with username couldn't be found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status4xxResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    Authorization:
      in: header
      name: Authorization
      schema:
        type: string
      required: true
  schemas:
    Specification:
      type: object
      required:
        - version
        - license
        - apiTitle
      properties:
        version:
          type: string
          pattern: '\d+\.\d+\.\d+'
        license:
          type: object
          required:
            - name
            - url
          properties:
            name:
              type: string
            url:
              type: string
        apiTitle:
          type: string
    GetProtectedUserResponse:
      type: object
      required:
        - username
        - displayName
        - role
      properties:
        username:
          type: string
        displayName:
          type: string
        role:
          $ref: '#/components/schemas/UserRole'
    GetUserProfileResponse:
      type: object
      required:
        - username
        - fullName
        - email
        - displayName
        - role
      properties:
        username:
          type: string
        fullName:
          type: string
        email:
          type: string
        displayName:
          type: string
        role:
          $ref: '#/components/schemas/UserRole'
    UpdateUserProfileRequest:
      type: object
      required:
        - fullName
        - email
        - displayName
      properties:
        fullName:
          type: string
        email:
          type: string
        displayName:
          type: string
    UserRole:
      type: string
      enum:
        - reviewer
        - supervisor
        - admin
    Status4xxResponse:
      type: object
      required:
        - reason
      properties:
        reason:
          type: string
    Status400Response:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/BadRequestBodyError"
    BadRequestBodyError:
      type: object
      required:
        - fields
        - reason
        - errorCode
      properties:
        fields:
          type: array
          items:
            type: string
        reason:
          type: string
        errorCode:
          type: string